spring:
  application:
    name: api-gateway
server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/
zuul:
  routes:
    hello:
      path: /hello-service/**
      service-id: hello-service
  filter:
    root: filter
    interval: 5