spring:
  application:
    name: api-gateway
server:
  port: 5555
zuul:
  routes:
    api-a:
      path: /a/**
      serviceId: hello-service
    api-b:
      path: /b/**
      serviceId: feign-consumer
  ThrowExceptionFilter:
    pre:
      disable: true
  AccessFilter:
    pre:
      disable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka,http://localhost:1112/eureka