server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/
#spring:
#  zipkin:
#    base-url: http://localhost:9411
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud
